//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZcadDebuger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eZcadDebuger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///符号	含义	示例	匹配的示例
        ///
        ///--------------------------------------------------------------------------------
        ///
        ///*	可以重复0次或多次的前导字符  ra*t    rt、rat、raat和raaat 等
        ///+	可以重复1次或多次的前导字符	ra+t    rat、raat和raaat等（但不能是rt)
        ///?	可以重复0次或1次的前导字符	ra?t    只有rt和rat匹配
        ///
        ///{n} 精确匹配 n 次。比如“a{3}”表示连续出现三个a。
        ///{n,}	至少匹配 n 次。
        ///{n,m}	匹配 n 到 m 次。
        ///
        ///--------------------------------------------------------------------------------
        ///
        ///^	匹配必须出现在字符串或者一行的开头	^B  B,但只能是文本中的第一个字符
        ///$	输入文本的结尾	X$  X,但只能是文本中的最后一个字符
        ///
        ///\b	字边界	ion\b	以ion结尾的任何字，而\ba表示以a开头的任何字
        ///\B	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegexTips {
            get {
                return ResourceManager.GetString("RegexTips", resourceCulture);
            }
        }
    }
}
